#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo "🙈 Afraid to look! Your styling needs fixing. 🙈
            Prettier Check Failed. Run npm run format, add changes and try commit again.";
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤😡😤 Your failure to adhere to our standards is disappointing. Try again. 😤😡😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌🔍 Upon closer inspection, your Types failed. 🔎❌
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false;
)

# If everything passes... Now we can commit
echo '✅🐢✅🐢 Oogway approves... Your contribution is appreciated and accepted for commit. ✅🐢✅🐢'
